### ISSUE TITLE
NPE with Picasso

### ISSUE THREAD

**Issue by rusmichal** [adamstyrc/cookie-cutter#4]
Hello I use your `CookieCutterImageView` with Picasso to load image. 

Usage in fragment:

`Picasso.with(getContext()).load(uri).into(cutterImageView);`

But I got error:

```
Process: com.mooduplabs.qrcontacts, PID: 26824
                  java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap android.graphics.drawable.BitmapDrawable.getBitmap()' on a null object reference
                      at com.adamstyrc.cookiecutter.CookieCutterImageView.getBitmap(CookieCutterImageView.java:171)
                      at com.adamstyrc.cookiecutter.CookieCutterImageView.setImageCentered(CookieCutterImageView.java:75)
                      at com.adamstyrc.cookiecutter.CookieCutterImageView.onImageLoaded(CookieCutterImageView.java:69)
                      at com.adamstyrc.cookiecutter.CookieCutterImageView.access$000(CookieCutterImageView.java:21)
                      at com.adamstyrc.cookiecutter.CookieCutterImageView$1.onGlobalLayout(CookieCutterImageView.java:61)
                      at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:986)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2206)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1297)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7011)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:590)
                      at android.view.Choreographer.doFrame(Choreographer.java:560)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:145)
                      at android.app.ActivityThread.main(ActivityThread.java:6938)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by dave-kennedy** [comment]
This is still occurring with version 1.0.2.
